import * as z from 'zod/v4';
import { logger } from '../utils/logger.js';
import { generateStructured } from './claude.js';
import { recordClassification } from './aiAudit.js';
import { getAiConfig } from './appConfig.js';
import { toUserContent, type CustomerImage } from './attachments.js';
import { buildPrompt, type PromptContext } from '../utils/promptBuilder.js';
import type { AiConfig } from '../types/config.js';

function buildClassifierUserPrompt(
  ctx: PromptContext,
  currentLabels: string[],
): string {
  const existing =
    currentLabels.length > 0 ? currentLabels.join(', ') : '(none)';
  return [
    `Labels already on this conversation: ${existing}`,
    '',
    'Conversation and customer context:',
    buildPrompt(ctx),
  ].join('\n');
}

/**
 * The classification labels the AI is allowed to assign. Action labels
 * (refund-30/50/70/full, reshipped, changed-address, changed-contact,
 * sub-cancelled, sub-cancelled-ai) are NEVER assignable by the classifier —
 * they record actions taken by an agent/tool.
 */
export const CLASSIFICATION_LABELS = [
  'business',
  'change-address',
  'change-contact',
  'sub-cancel',
  'refund',
  'discount-issue',
  'missing-packs',
  'no-country',
  'not-delivered',
  'order-status',
  'product-defect',
  'other',
] as const;

export type ClassificationLabel = (typeof CLASSIFICATION_LABELS)[number];

const ClassificationSchema = z.object({
  reasoning: z
    .string()
    .describe('One or two short sentences explaining the labels and current intents.'),
  labels: z
    .array(z.enum(CLASSIFICATION_LABELS))
    .describe('Every intent the customer has raised anywhere in this conversation (used for tagging).'),
  currentIntents: z
    .array(z.enum(CLASSIFICATION_LABELS))
    .describe(
      "Intents that need handling NOW: what the customer's latest unanswered message(s) ask for, plus earlier requests that are still unresolved. Empty when nothing needs handling.",
    ),
  needsReply: z
    .boolean()
    .describe(
      'False when the latest unanswered message(s) need no response: a thank-you / ok / closing message, an automatic reply or bounce, or unsolicited spam. True otherwise.',
    ),
  isAutoReply: z
    .boolean()
    .describe(
      'True when the latest unanswered message(s) were generated by a machine (out-of-office, auto-acknowledgement, bounce, ticket-system or platform notification).',
    ),
  isSpam: z
    .boolean()
    .describe(
      'True for unsolicited outreach that is not from a customer: sales/agency/software pitches, commission or "X orders" offers, review-site or ad-platform marketing, supplier offers, phishing. False for anyone with an order or a customer question.',
    ),
  language: z
    .string()
    .describe("Language of the customer's latest message as an English name, e.g. \"English\", \"Swedish\"."),
});

/** A classifier decision for one conversation. */
export interface Classification {
  reasoning: string;
  /** All intents raised in the conversation (Chatwoot tagging, add-only). */
  labels: ClassificationLabel[];
  /** Intents that need handling now (routing). */
  currentIntents: ClassificationLabel[];
  needsReply: boolean;
  isAutoReply: boolean;
  isSpam: boolean;
  language: string;
}

function normalize(result: z.infer<typeof ClassificationSchema>): Classification {
  return {
    reasoning: result.reasoning,
    labels: Array.from(new Set(result.labels)),
    currentIntents: Array.from(new Set(result.currentIntents)),
    needsReply: result.needsReply,
    isAutoReply: result.isAutoReply,
    isSpam: result.isSpam,
    language: result.language,
  };
}

/**
 * Classifies a conversation. Customer images, when provided, are shown to the
 * model (photo-only messages are otherwise unclassifiable). Returns null on
 * failure (callers should treat that as "hand off to be safe").
 */
export async function classifyConversation(
  ctx: PromptContext,
  currentLabels: string[],
  images: CustomerImage[] = [],
): Promise<Classification | null> {
  const cfg = await getAiConfig();
  const userPrompt = buildClassifierUserPrompt(ctx, currentLabels);

  const result = await generateStructured(
    cfg.classifierSystemPrompt,
    toUserContent(userPrompt, images),
    ClassificationSchema,
    {
      model: cfg.classifierModel,
      maxTokens: cfg.classifierMaxTokens,
      effort: cfg.classifierEffort,
      meta: { kind: 'classify', conversationId: ctx.conversationId },
    },
  );

  if (!result) {
    logger.warn('Conversation classification returned no result', {
      conversationId: ctx.conversationId,
    });
    return null;
  }

  const classification = normalize(result);
  logger.info('Classified conversation', {
    conversationId: ctx.conversationId,
    ...classification,
  });
  // Persist the classification decision (best-effort audit).
  void recordClassification({
    conversationId: ctx.conversationId,
    model: cfg.classifierModel,
    ...classification,
  });
  return classification;
}

/**
 * Runs the classifier for the admin prompt tester and returns the exact prompts
 * plus the result. Does NOT persist a classification decision or write any
 * labels — purely for inspection/debugging.
 */
export async function classifyForReplay(
  ctx: PromptContext,
  currentLabels: string[],
  cfg: Pick<
    AiConfig,
    'classifierSystemPrompt' | 'classifierModel' | 'classifierMaxTokens' | 'classifierEffort'
  >,
  images: CustomerImage[] = [],
): Promise<{
  systemPrompt: string;
  userPrompt: string;
  model: string;
  classification: Classification | null;
}> {
  const systemPrompt = cfg.classifierSystemPrompt;
  const userPrompt = buildClassifierUserPrompt(ctx, currentLabels);

  const result = await generateStructured(
    systemPrompt,
    toUserContent(userPrompt, images),
    ClassificationSchema,
    {
      model: cfg.classifierModel,
      maxTokens: cfg.classifierMaxTokens,
      effort: cfg.classifierEffort,
      meta: { kind: 'classify-replay', conversationId: ctx.conversationId },
    },
  );

  return {
    systemPrompt,
    userPrompt,
    model: cfg.classifierModel,
    classification: result ? normalize(result) : null,
  };
}
