export interface AiDraft {
  conversationId: number;
  contactId: number | null;
  // Customer-facing reply (safe to send).
  response: string;
  // Agent-only note, never sent to the customer. Null when not warranted.
  noteToAgent: string | null;
  model: string;
  generatedAt: string;
  // 'auto' = generated by the incoming-message webhook; 'manual' = generated
  // on demand from the dashboard composer.
  source: 'auto' | 'manual';
}
